### PR TITLE
Updating MP 1.2 to include new features

### PR DESCRIPTION
**Pull request by kwsutter**
Updated the MP 1.2 spec to include the new propose feature updates.  Also, did a bit more cleanup to get rid of the "bom" designation.

### CODE REVIEW

**Comment by kwsutter** [comment]
Stupid me...  I used the github tool to resolve a potential merge conflict with the REAMDE.adoc file...  Now I have the IP validation issue.  From our past experiences with this type of situation, I think we can safely ignore this when merging since we know the origin of the changes (me).  Thanks.

**Comment by johnament** [comment]
I would not have recommended doing this to be honest.  We're back to mixing time boxed releases vs content based releases.

**Comment by kwsutter** [comment]
Not sure I understand your concern, @johnament.  I'm working on 1.2-SNAPSHOT for the MicroProfile release.  So, I'm making the initial changes to the pom files to pull in the expected content for MP 1.2, which we are planning in time for JavaOne.  I'd like to create RCn drivers as we go along here.  If some component decides they can't make the cutoff for their respective release, then I would modify the pom before MP 1.2 goes final.  I'm still driving towards what I believe is a time-boxed release.  What am I doing out of sorts?  Thanks.

**Comment by johnament** [comment]
You can cut an RC when we have RC's or final builds of the specs.  When we have 100% on target that a spec is going to make it, that's when this should be updated with that spec's changes.

When we spoke about https://groups.google.com/forum/#!topic/microprofile/pgZ9XAEdXPw on the call, I had explicitly stated it was on the person driving those specs forward to get their spec into this BOM.

**Comment by kwsutter** [comment]
@johnament, I didn't catch that nuance that it was up to the component to drive the change into the bom...   And, to be honest, I don't know if I agree that it has to be up to the component...  I also want to start these RCs before the other components are "complete" because we're basically on the same schedule -- get done by JavaOne.  Maybe for the next MP release, we'll have to announce when the train is leaving to allow sufficient lead time to complete the components' efforts.  But, with the IP reviews, etc that are required for the full MP releases, this approach might be difficult as well...  Having all of the MP components within the same Eclipse MP project complicates the release processes.  Now I'm rambling...

**Comment by johnament** [comment]
Ok, sorry if that wasn't clear.  But if it wasn't, how come you didn't raise a question over https://github.com/eclipse/microprofile-bom/pull/30 ?

**Comment by kwsutter** [comment]
I thought PR #30 was a test bug report for Eclipse...  I didn't think it was a real PR.

**Pull request merged**
