### PR TITLE
Adding a short listing of default properties available in MicroProfil…

### PR DESCRIPTION
**Pull request by johnament**
…e 1.1 runtimes.

### CODE REVIEW

**Comment by NottyCode** [comment]
I'm trying to work out how to use this information in an application and I'm not sure I can (well the host name seems ok), but I can't tell whether http or https is being used, or which port the request came in on which makes me think the utility of these properties is low. I think I'd want to be able to understand which port the request came in on. I'm assuming you are hoping to allow an http request to be redirected to https via these properties, but given you don't know which it came in on I'm not sure.

**Comment by OndrejM** [comment]
If there's no clear agreement before end of June, this proposal should be postponed to MicroProfile 1.2. We want to release 1.1 ASAP, basically waiting for Config 1.0 and resolving IP issues.

> I can't tell whether http or https is being used

I think the proposal targets port bindings, not the port used for the current request, right? In that case, it should be clear on which ports the runtime listens for requests - the runtime knows to which listeners the app is bound and whether they are HTTP or HTTPS listeners, right? If there are more listeners, one of them should be picked - it doesn't matter which one and there's no guarantee that the port number will always stay the same. We could also define additional properties `http.ports` and `https.ports` to give a comma-separated list of ports.

**Comment by Emily-Jiang** [comment]
As we discussed on the google group, the PR should be opened against this spec's own repo. It will be easily to maintain or vote. The MP project release such as 1.1, 1.2 should just the aggregation of the specs, nothing more.

**Comment by johnament** [comment]
@Emily-Jiang  so that's the thing, I'm not sure this is a spec by itself.  Maybe it has a TCK? I doubt it though.  I figure this repo is the equivalent of the EE repo for providing platform level requirements which I feel this change is included in.  Also, can you link to the group email? I don't see it.

**Comment by johnament** [comment]
@NottyCode @OndrejM As stated before, I'm not in any rush to force a feature like this in to MP.  This is a "merge when ready" situation.  I agree, this isn't "which port the request came in on" but instead "what port is my application using".  I believe the few things we spoke about in the past are:

- Different servers allow a user to configure a port per application, or a global listener port.  The ports used here are those ports, from an application's point of view I'm asking for *my* port which is  either the per application or the global version.  Swarm, Hammock, Meecrowave support single ports.  WLP, Payara support per application ports.

- Another issue is whether or not I'm using HTTPS.  

- Granted, my original prototype (within Hammock) was a `HammockRuntime` class which if applied to Microprofile could look something like this:

```java
public interface MicroprofileRuntime {
  boolean isSecure();
  String getListenAddress();
  int getListenPort();
}
```

**Comment by Emily-Jiang** [comment]
I referred to [here](https://groups.google.com/forum/#!topic/microprofile/ELGrUejCoIA), where Kevin and I suggested not to directly do a PR against the bom, but on its own repo.

**Comment by kwsutter** [comment]
Because of the needed context to fully explain the use of these properties, I think this type of update needs to be in it's own doc repo...  We don't really have a doc repo yet for MP, do we?  Unless we consider the microprofile repo as our doc repo?  I would rather keep the microprofile-bom repo as clean and simple as possible.

**Comment by pilhuhn** [comment]
Do you only intend to have settable properties? 
I think read-only ones like `microprofile.version` may be helpful too

**Comment by OndrejM** [comment]
Closing this PR as this should go to a separate proposal as discussed before.

**Pull request closed without merging**
